/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEpochStrategy, IEpochStrategyInterface } from "../../interfaces/IEpochStrategy.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "auctionEnd",
        "type": "uint256"
      }
    ],
    "name": "AuctionStillOpen",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "floor",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "bid",
        "type": "uint256"
      }
    ],
    "name": "BidBelowFloor",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "minBid",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "bid",
        "type": "uint256"
      }
    ],
    "name": "BidTooLow",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "expiry",
        "type": "uint256"
      }
    ],
    "name": "EpochNotExpired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotVault",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NothingBid",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "cap",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "premium",
        "type": "uint256"
      }
    ],
    "name": "PremiumAboveBound",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "enum IEpochStrategy.State",
        "name": "expected",
        "type": "uint8"
      },
      {
        "internalType": "enum IEpochStrategy.State",
        "name": "actual",
        "type": "uint8"
      }
    ],
    "name": "StateMismatch",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "epochId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "winner",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "premium",
        "type": "uint256"
      }
    ],
    "name": "AuctionClosed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "epochId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "newEnd",
        "type": "uint256"
      }
    ],
    "name": "AuctionExtended",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "epochId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "bidder",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "BidPlaced",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "epochId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "notional",
        "type": "uint256"
      }
    ],
    "name": "EpochRolled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "epochId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "spotAtExpiry",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "payoff",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "premium",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "kept",
        "type": "uint256"
      }
    ],
    "name": "EpochSettled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "epochId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "notional",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "strike",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "spot",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "auctionEnd",
        "type": "uint256"
      }
    ],
    "name": "EpochStarted",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "bid",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "closeAuction",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "currentEpoch",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint128",
            "name": "id",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "notional",
            "type": "uint128"
          },
          {
            "internalType": "uint64",
            "name": "start",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "auctionEnd",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "expiry",
            "type": "uint64"
          },
          {
            "internalType": "uint96",
            "name": "strike",
            "type": "uint96"
          },
          {
            "internalType": "uint96",
            "name": "spot",
            "type": "uint96"
          },
          {
            "internalType": "address",
            "name": "highBidder",
            "type": "address"
          },
          {
            "internalType": "uint96",
            "name": "highBid",
            "type": "uint96"
          },
          {
            "internalType": "uint256",
            "name": "extensionCount",
            "type": "uint256"
          }
        ],
        "internalType": "struct IEpochStrategy.Epoch",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "settleEpoch",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "startEpoch",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "state",
    "outputs": [
      {
        "internalType": "enum IEpochStrategy.State",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "vault",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IEpochStrategy__factory {
    static readonly abi = _abi;
    static createInterface(): IEpochStrategyInterface {
      return new Interface(_abi) as IEpochStrategyInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEpochStrategy {
      return new Contract(address, _abi, runner) as unknown as IEpochStrategy;
    }
  }
  