/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEqueRouter, IEqueRouterInterface } from "../../interfaces/IEqueRouter.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "capBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "requestedBps",
        "type": "uint256"
      }
    ],
    "name": "CapExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NothingToRebalance",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "currentBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "targetBps",
        "type": "uint256"
      }
    ],
    "name": "RebalanceRejected",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StrategyLocked",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnknownStrategy",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnknownVault",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "totalBps",
        "type": "uint256"
      }
    ],
    "name": "WeightsInvalid",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "vault",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "epochAssets",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "lendingAssets",
        "type": "uint256"
      }
    ],
    "name": "Rebalanced",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "vault",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "strategy",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "capBps",
        "type": "uint256"
      }
    ],
    "name": "StrategyRegistered",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "vault",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "epochBps",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "lendingBps",
        "type": "uint256"
      }
    ],
    "name": "WeightsSet",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "vault",
        "type": "address"
      }
    ],
    "name": "nextEpochBoundary",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "vault",
        "type": "address"
      }
    ],
    "name": "planAllocation",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "strategies",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "amounts",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "vault",
        "type": "address"
      }
    ],
    "name": "rebalance",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "vault",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "strategy",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "capBps",
        "type": "uint256"
      }
    ],
    "name": "registerStrategy",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "bps",
        "type": "uint256"
      }
    ],
    "name": "setToleranceBps",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "vault",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "epochBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "lendingBps",
        "type": "uint256"
      }
    ],
    "name": "setWeights",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "vault",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "strategy",
        "type": "address"
      }
    ],
    "name": "strategyAssets",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "vault",
        "type": "address"
      }
    ],
    "name": "strategyHoldings",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "strategies",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "holdings",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "vault",
        "type": "address"
      }
    ],
    "name": "strategyLocked",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "toleranceBps",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "vault",
        "type": "address"
      }
    ],
    "name": "weights",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "epochBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "lendingBps",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IEqueRouter__factory {
    static readonly abi = _abi;
    static createInterface(): IEqueRouterInterface {
      return new Interface(_abi) as IEqueRouterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEqueRouter {
      return new Contract(address, _abi, runner) as unknown as IEqueRouter;
    }
  }
  