/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockSequencerFeed, MockSequencerFeedInterface } from "../../oracle/MockSequencerFeed.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "keeper_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "NotKeeper",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "decimals",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "description",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint80",
        "name": "_roundId",
        "type": "uint80"
      }
    ],
    "name": "getRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "roundId",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "answer",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "startedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "updatedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "answeredInRound",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "keeper",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "latestRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "roundId",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "answer",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "startedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "updatedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "answeredInRound",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "up",
        "type": "bool"
      }
    ],
    "name": "setUp",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "version",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x3460245763000002bc8038038091608039608081019081604052601f81136028575b50505b5f5ffd5b608051905f1960601c821115603c57506021565b81605c5791505063d92e233d60e01b608082015260846040518092030190fd5b5060015f555f1960a01b6002541617600255426001556300000236809163000000869039604051f3fe60806040523460115760033611610109575b5f5ffd5b50602060043603126011576001600435116011575f1960601c60025433181661016d576004355f5542600155005b505f610100565b50602060c0527f6d6f636b2073657175656e63657220757074696d65000000000000000000000060a052601560e052601560a06101005e5f61011552606060c0f35b6020600436031260115769ffffffffffffffffffff600435116011576004351561017e5760c6608060015460043590805f546004356101bc565b610164565b505f1960601c60025416610100565b632d607098637fffffff82161460155763313ce56781146043576354fd4d500360115760015b60805260206080f35b5f3560e01c633942720b60e11b5f351060da5763aced1660811361013e57637284e4168114604a57639a6fc8f514608c576011565b63aced1661811460cb5763feaf968c03601157610163608060018054805f54836101bc565b5b60405180910390f35b631ea2564f60e31b60805260046080fd5b62461bcd60e51b608052600d60a4527f6e6f207375636820726f756e640000000000000000000000000000000000000060c452602060845260646080fd5b939269ffffffffffffffffffff938493929316866080015285606001528460400152836020015216815260a0019056fea264697066735822122046241f0af21e227a6dfe5bfdc3925e28e6a540035860cf6ddfdf96e87d4f88e864736f6c637816736f6c783a302e312e383b736f6c633a302e382e33340047";

  
      type MockSequencerFeedConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockSequencerFeedConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockSequencerFeed__factory extends ContractFactory {
    
      constructor(...args: MockSequencerFeedConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(keeper_: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(keeper_, overrides || {});
    };
    override deploy(keeper_: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(keeper_, overrides || {}) as Promise<MockSequencerFeed & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockSequencerFeed__factory {
      return super.connect(runner) as MockSequencerFeed__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockSequencerFeedInterface {
      return new Interface(_abi) as MockSequencerFeedInterface;
    }
    
    override attach(address: string | Addressable): MockSequencerFeed {
      return super.attach(address) as MockSequencerFeed;
    }
  static connect(address: string, runner?: ContractRunner | null): MockSequencerFeed {
      return new Contract(address, _abi, runner) as unknown as MockSequencerFeed;
    }
  }

  
  