/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockSequencerFeed } from './MockSequencerFeed.js';
export type { MockV3Aggregator } from './MockV3Aggregator.js';