/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IEpochStrategy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEpochStrategy__factory>
getContractFactory(name: 'IEqueVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEqueVault__factory>
getContractFactory(name: 'IEqueRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEqueRouter__factory>
getContractFactory(name: 'IStrategy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStrategy__factory>
getContractFactory(name: 'Errors', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Errors__factory>
getContractFactory(name: 'EpochMath', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EpochMath__factory>
getContractFactory(name: 'EqueAccess', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EqueAccess__factory>

  getContractAt(name: 'IEpochStrategy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEpochStrategy>
getContractAt(name: 'IEqueVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEqueVault>
getContractAt(name: 'IEqueRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEqueRouter>
getContractAt(name: 'IStrategy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStrategy>
getContractAt(name: 'Errors', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Errors>
getContractAt(name: 'EpochMath', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EpochMath>
getContractAt(name: 'EqueAccess', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EqueAccess>

  deployContract(name: 'IEpochStrategy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEpochStrategy>
deployContract(name: 'IEqueVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEqueVault>
deployContract(name: 'IEqueRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEqueRouter>
deployContract(name: 'IStrategy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStrategy>
deployContract(name: 'Errors', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Errors>
deployContract(name: 'EpochMath', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EpochMath>
deployContract(name: 'EqueAccess', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EqueAccess>

  deployContract(name: 'IEpochStrategy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEpochStrategy>
deployContract(name: 'IEqueVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEqueVault>
deployContract(name: 'IEqueRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEqueRouter>
deployContract(name: 'IStrategy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStrategy>
deployContract(name: 'Errors', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Errors>
deployContract(name: 'EpochMath', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EpochMath>
deployContract(name: 'EqueAccess', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EqueAccess>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  