/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TestnetFaucetInterface extends Interface {
    getFunction(nameOrSignature: "bidderLastClaim" | "bidderTab" | "claimBidder" | "claimDepositor" | "depositorLastClaim" | "depositorTab" | "drain" | "nextBidderClaim" | "nextDepositorClaim" | "owner" | "setBidderTab" | "setDepositorTab"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Claimed"): EventFragment;

    encodeFunctionData(functionFragment: 'bidderLastClaim', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'bidderTab', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimBidder', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimDepositor', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositorLastClaim', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'depositorTab', values?: undefined): string;
encodeFunctionData(functionFragment: 'drain', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextBidderClaim', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nextDepositorClaim', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'setBidderTab', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDepositorTab', values: [AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'bidderLastClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bidderTab', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimBidder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimDepositor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositorLastClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositorTab', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'drain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextBidderClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextDepositorClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBidderTab', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDepositorTab', data: BytesLike): Result;
  }

  
    export namespace ClaimedEvent {
      export type InputTuple = [wallet: AddressLike, bidder: boolean, amount: BigNumberish];
      export type OutputTuple = [wallet: string, bidder: boolean, amount: bigint];
      export interface OutputObject {wallet: string, bidder: boolean, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TestnetFaucet extends BaseContract {
    
    connect(runner?: ContractRunner | null): TestnetFaucet;
    waitForDeployment(): Promise<this>;

    interface: TestnetFaucetInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bidderLastClaim: TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    bidderTab: TypedContractMethod<
      [],
      [[string, bigint, bigint] & {token: string, amount: bigint, interval: bigint }],
      'view'
    >
    

    
    claimBidder: TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >
    

    
    claimDepositor: TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >
    

    
    depositorLastClaim: TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    depositorTab: TypedContractMethod<
      [],
      [[string, bigint, bigint] & {token: string, amount: bigint, interval: bigint }],
      'view'
    >
    

    
    drain: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    nextBidderClaim: TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    nextDepositorClaim: TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setBidderTab: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, interval: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setDepositorTab: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, interval: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bidderLastClaim'): TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bidderTab'): TypedContractMethod<
      [],
      [[string, bigint, bigint] & {token: string, amount: bigint, interval: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'claimBidder'): TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimDepositor'): TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositorLastClaim'): TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'depositorTab'): TypedContractMethod<
      [],
      [[string, bigint, bigint] & {token: string, amount: bigint, interval: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'drain'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextBidderClaim'): TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextDepositorClaim'): TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setBidderTab'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, interval: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDepositorTab'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, interval: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Claimed'): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;

    filters: {
      
      'Claimed(address,bool,uint256)': TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
      Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
    
    };
  }