/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface EqueVaultInterface extends Interface {
    getFunction(nameOrSignature: "CURATOR_ROLE" | "DEFAULT_ADMIN_ROLE" | "GUARDIAN_ROLE" | "KEEPER_ROLE" | "allocate" | "allowance" | "approve" | "asset" | "balanceOf" | "cap" | "claim" | "convertToAssets" | "convertToShares" | "decimals" | "deposit" | "depositFeeBps" | "feeRecipient" | "freeAssets" | "getRoleAdmin" | "grantRole" | "hasRole" | "initialize" | "lockedAssets" | "maxDeposit" | "maxMint" | "maxRedeem" | "maxWithdraw" | "mint" | "name" | "pause" | "paused" | "previewDeposit" | "previewMint" | "previewRedeem" | "previewWithdraw" | "redeem" | "redeemPending" | "redeemReadyAt" | "renounceRole" | "requestRedeem" | "revokeRole" | "router" | "router_" | "setCap" | "setFeeRecipient" | "setFees" | "supportsInterface" | "symbol" | "syncAssets" | "totalAssets" | "totalSupply" | "transfer" | "transferFrom" | "unpause" | "withdraw" | "withdrawFeeBps"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Allocated" | "Allocating" | "Approval" | "CapSet" | "Deposit" | "EpochBoundary" | "FeeRecipientSet" | "FeesSet" | "Initialized" | "Paused" | "RedeemClaimed" | "RedeemRequested" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Transfer" | "Unpaused" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'CURATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'GUARDIAN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'KEEPER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'allocate', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'asset', values?: undefined): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cap', values?: undefined): string;
encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
encodeFunctionData(functionFragment: 'convertToAssets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'convertToShares', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'depositFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'freeAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, string, string, AddressLike, AddressLike, BigNumberish, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockedAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxDeposit', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxMint', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxRedeem', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxWithdraw', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'mint', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'previewDeposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'previewMint', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'previewRedeem', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'previewWithdraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'redeem', values: [BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'redeemPending', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'redeemReadyAt', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'requestRedeem', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'router', values?: undefined): string;
encodeFunctionData(functionFragment: 'router_', values?: undefined): string;
encodeFunctionData(functionFragment: 'setCap', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setFeeRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setFees', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'syncAssets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawFeeBps', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'CURATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GUARDIAN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'KEEPER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allocate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'asset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'convertToAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'convertToShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freeAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxRedeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewRedeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeemPending', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeemReadyAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestRedeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'router', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'router_', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'syncAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFeeBps', data: BytesLike): Result;
  }

  
    export namespace AllocatedEvent {
      export type InputTuple = [assets: BigNumberish];
      export type OutputTuple = [assets: bigint];
      export interface OutputObject {assets: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AllocatingEvent {
      export type InputTuple = [assets: BigNumberish];
      export type OutputTuple = [assets: bigint];
      export interface OutputObject {assets: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CapSetEvent {
      export type InputTuple = [cap: BigNumberish];
      export type OutputTuple = [cap: bigint];
      export interface OutputObject {cap: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEvent {
      export type InputTuple = [sender: AddressLike, owner: AddressLike, assets: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [sender: string, owner: string, assets: bigint, shares: bigint];
      export interface OutputObject {sender: string, owner: string, assets: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochBoundaryEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeRecipientSetEvent {
      export type InputTuple = [recipient: AddressLike];
      export type OutputTuple = [recipient: string];
      export interface OutputObject {recipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesSetEvent {
      export type InputTuple = [depositBps: BigNumberish, withdrawBps: BigNumberish];
      export type OutputTuple = [depositBps: bigint, withdrawBps: bigint];
      export interface OutputObject {depositBps: bigint, withdrawBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedeemClaimedEvent {
      export type InputTuple = [owner: AddressLike, assets: BigNumberish];
      export type OutputTuple = [owner: string, assets: bigint];
      export interface OutputObject {owner: string, assets: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedeemRequestedEvent {
      export type InputTuple = [owner: AddressLike, shares: BigNumberish, assets: BigNumberish, readyAt: BigNumberish];
      export type OutputTuple = [owner: string, shares: bigint, assets: bigint, readyAt: bigint];
      export interface OutputObject {owner: string, shares: bigint, assets: bigint, readyAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [sender: AddressLike, receiver: AddressLike, owner: AddressLike, assets: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [sender: string, receiver: string, owner: string, assets: bigint, shares: bigint];
      export interface OutputObject {sender: string, receiver: string, owner: string, assets: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EqueVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): EqueVault;
    waitForDeployment(): Promise<this>;

    interface: EqueVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CURATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    GUARDIAN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    KEEPER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allocate: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    asset: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    cap: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >
    

    
    convertToAssets: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    convertToShares: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [assets: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    depositFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    freeAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [underlying: AddressLike, name_: string, symbol_: string, admin: AddressLike, routerAddress: AddressLike, cap_: BigNumberish, feeRecipient_: AddressLike, depositFeeBps_: BigNumberish, withdrawFeeBps_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    lockedAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxDeposit: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    maxMint: TypedContractMethod<
      [receiver: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    maxRedeem: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    maxWithdraw: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [shares: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    previewDeposit: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    previewMint: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    previewRedeem: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    previewWithdraw: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    redeem: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, arg2: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    redeemPending: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    redeemReadyAt: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    requestRedeem: TypedContractMethod<
      [shares: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    router: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    router_: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setCap: TypedContractMethod<
      [cap_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeRecipient: TypedContractMethod<
      [recipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFees: TypedContractMethod<
      [depositFeeBps_: BigNumberish, withdrawFeeBps_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    syncAssets: TypedContractMethod<
      [delta: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, arg2: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    withdrawFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CURATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'GUARDIAN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'KEEPER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allocate'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'asset'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cap'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'convertToAssets'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'convertToShares'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [assets: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'freeAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [underlying: AddressLike, name_: string, symbol_: string, admin: AddressLike, routerAddress: AddressLike, cap_: BigNumberish, feeRecipient_: AddressLike, depositFeeBps_: BigNumberish, withdrawFeeBps_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lockedAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxDeposit'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxMint'): TypedContractMethod<
      [receiver: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxRedeem'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxWithdraw'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [shares: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'previewDeposit'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewMint'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewRedeem'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewWithdraw'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, arg2: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redeemPending'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redeemReadyAt'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestRedeem'): TypedContractMethod<
      [shares: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'router'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'router_'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setCap'): TypedContractMethod<
      [cap_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeRecipient'): TypedContractMethod<
      [recipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFees'): TypedContractMethod<
      [depositFeeBps_: BigNumberish, withdrawFeeBps_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'syncAssets'): TypedContractMethod<
      [delta: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, arg2: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Allocated'): TypedContractEvent<AllocatedEvent.InputTuple, AllocatedEvent.OutputTuple, AllocatedEvent.OutputObject>;
getEvent(key: 'Allocating'): TypedContractEvent<AllocatingEvent.InputTuple, AllocatingEvent.OutputTuple, AllocatingEvent.OutputObject>;
getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'CapSet'): TypedContractEvent<CapSetEvent.InputTuple, CapSetEvent.OutputTuple, CapSetEvent.OutputObject>;
getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'EpochBoundary'): TypedContractEvent<EpochBoundaryEvent.InputTuple, EpochBoundaryEvent.OutputTuple, EpochBoundaryEvent.OutputObject>;
getEvent(key: 'FeeRecipientSet'): TypedContractEvent<FeeRecipientSetEvent.InputTuple, FeeRecipientSetEvent.OutputTuple, FeeRecipientSetEvent.OutputObject>;
getEvent(key: 'FeesSet'): TypedContractEvent<FeesSetEvent.InputTuple, FeesSetEvent.OutputTuple, FeesSetEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RedeemClaimed'): TypedContractEvent<RedeemClaimedEvent.InputTuple, RedeemClaimedEvent.OutputTuple, RedeemClaimedEvent.OutputObject>;
getEvent(key: 'RedeemRequested'): TypedContractEvent<RedeemRequestedEvent.InputTuple, RedeemRequestedEvent.OutputTuple, RedeemRequestedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'Allocated(uint256)': TypedContractEvent<AllocatedEvent.InputTuple, AllocatedEvent.OutputTuple, AllocatedEvent.OutputObject>;
      Allocated: TypedContractEvent<AllocatedEvent.InputTuple, AllocatedEvent.OutputTuple, AllocatedEvent.OutputObject>;
    

      'Allocating(uint256)': TypedContractEvent<AllocatingEvent.InputTuple, AllocatingEvent.OutputTuple, AllocatingEvent.OutputObject>;
      Allocating: TypedContractEvent<AllocatingEvent.InputTuple, AllocatingEvent.OutputTuple, AllocatingEvent.OutputObject>;
    

      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'CapSet(uint256)': TypedContractEvent<CapSetEvent.InputTuple, CapSetEvent.OutputTuple, CapSetEvent.OutputObject>;
      CapSet: TypedContractEvent<CapSetEvent.InputTuple, CapSetEvent.OutputTuple, CapSetEvent.OutputObject>;
    

      'Deposit(address,address,uint256,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'EpochBoundary()': TypedContractEvent<EpochBoundaryEvent.InputTuple, EpochBoundaryEvent.OutputTuple, EpochBoundaryEvent.OutputObject>;
      EpochBoundary: TypedContractEvent<EpochBoundaryEvent.InputTuple, EpochBoundaryEvent.OutputTuple, EpochBoundaryEvent.OutputObject>;
    

      'FeeRecipientSet(address)': TypedContractEvent<FeeRecipientSetEvent.InputTuple, FeeRecipientSetEvent.OutputTuple, FeeRecipientSetEvent.OutputObject>;
      FeeRecipientSet: TypedContractEvent<FeeRecipientSetEvent.InputTuple, FeeRecipientSetEvent.OutputTuple, FeeRecipientSetEvent.OutputObject>;
    

      'FeesSet(uint16,uint16)': TypedContractEvent<FeesSetEvent.InputTuple, FeesSetEvent.OutputTuple, FeesSetEvent.OutputObject>;
      FeesSet: TypedContractEvent<FeesSetEvent.InputTuple, FeesSetEvent.OutputTuple, FeesSetEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RedeemClaimed(address,uint256)': TypedContractEvent<RedeemClaimedEvent.InputTuple, RedeemClaimedEvent.OutputTuple, RedeemClaimedEvent.OutputObject>;
      RedeemClaimed: TypedContractEvent<RedeemClaimedEvent.InputTuple, RedeemClaimedEvent.OutputTuple, RedeemClaimedEvent.OutputObject>;
    

      'RedeemRequested(address,uint256,uint256,uint256)': TypedContractEvent<RedeemRequestedEvent.InputTuple, RedeemRequestedEvent.OutputTuple, RedeemRequestedEvent.OutputObject>;
      RedeemRequested: TypedContractEvent<RedeemRequestedEvent.InputTuple, RedeemRequestedEvent.OutputTuple, RedeemRequestedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'Withdraw(address,address,address,uint256,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }