/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace EqueVaultFactory {
      
    export type VaultSpecStruct = {underlying: AddressLike, name: string, symbol: string, cap: BigNumberish, feeRecipient: AddressLike, depositFeeBps: BigNumberish, withdrawFeeBps: BigNumberish, epochStrategy: AddressLike, lendingStrategy: AddressLike, epochCapBps: BigNumberish, lendingCapBps: BigNumberish, epochWeightBps: BigNumberish, lendingWeightBps: BigNumberish}

    export type VaultSpecStructOutput = [underlying: string, name: string, symbol: string, cap: bigint, feeRecipient: string, depositFeeBps: bigint, withdrawFeeBps: bigint, epochStrategy: string, lendingStrategy: string, epochCapBps: bigint, lendingCapBps: bigint, epochWeightBps: bigint, lendingWeightBps: bigint] & {underlying: string, name: string, symbol: string, cap: bigint, feeRecipient: string, depositFeeBps: bigint, withdrawFeeBps: bigint, epochStrategy: string, lendingStrategy: string, epochCapBps: bigint, lendingCapBps: bigint, epochWeightBps: bigint, lendingWeightBps: bigint }
  
    }

  export interface EqueVaultFactoryInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "deployVault" | "router" | "vaultCount" | "vaultImplementation" | "vaults"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RouterDeployed" | "VaultDeployed"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'deployVault', values: [EqueVaultFactory.VaultSpecStruct]): string;
encodeFunctionData(functionFragment: 'router', values?: undefined): string;
encodeFunctionData(functionFragment: 'vaultCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'vaultImplementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'vaults', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'router', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vaultCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vaultImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vaults', data: BytesLike): Result;
  }

  
    export namespace RouterDeployedEvent {
      export type InputTuple = [router: AddressLike];
      export type OutputTuple = [router: string];
      export interface OutputObject {router: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultDeployedEvent {
      export type InputTuple = [vault: AddressLike, underlying: AddressLike, router: AddressLike];
      export type OutputTuple = [vault: string, underlying: string, router: string];
      export interface OutputObject {vault: string, underlying: string, router: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EqueVaultFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): EqueVaultFactory;
    waitForDeployment(): Promise<this>;

    interface: EqueVaultFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    deployVault: TypedContractMethod<
      [spec: EqueVaultFactory.VaultSpecStruct, ],
      [string],
      'nonpayable'
    >
    

    
    router: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vaultCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vaultImplementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vaults: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deployVault'): TypedContractMethod<
      [spec: EqueVaultFactory.VaultSpecStruct, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'router'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vaultCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vaultImplementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vaults'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'RouterDeployed'): TypedContractEvent<RouterDeployedEvent.InputTuple, RouterDeployedEvent.OutputTuple, RouterDeployedEvent.OutputObject>;
getEvent(key: 'VaultDeployed'): TypedContractEvent<VaultDeployedEvent.InputTuple, VaultDeployedEvent.OutputTuple, VaultDeployedEvent.OutputObject>;

    filters: {
      
      'RouterDeployed(address)': TypedContractEvent<RouterDeployedEvent.InputTuple, RouterDeployedEvent.OutputTuple, RouterDeployedEvent.OutputObject>;
      RouterDeployed: TypedContractEvent<RouterDeployedEvent.InputTuple, RouterDeployedEvent.OutputTuple, RouterDeployedEvent.OutputObject>;
    

      'VaultDeployed(address,address,address)': TypedContractEvent<VaultDeployedEvent.InputTuple, VaultDeployedEvent.OutputTuple, VaultDeployedEvent.OutputObject>;
      VaultDeployed: TypedContractEvent<VaultDeployedEvent.InputTuple, VaultDeployedEvent.OutputTuple, VaultDeployedEvent.OutputObject>;
    
    };
  }