/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace IMorpho {
      
    export type MarketParamsStruct = {loanToken: AddressLike, collateralToken: AddressLike, oracle: AddressLike, irm: AddressLike, lltv: BigNumberish}

    export type MarketParamsStructOutput = [loanToken: string, collateralToken: string, oracle: string, irm: string, lltv: bigint] & {loanToken: string, collateralToken: string, oracle: string, irm: string, lltv: bigint }
  
    }

  export interface IMorphoInterface extends Interface {
    getFunction(nameOrSignature: "market" | "position" | "supply" | "withdraw"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'market', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'position', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supply', values: [IMorpho.MarketParamsStruct, BigNumberish, BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [IMorpho.MarketParamsStruct, BigNumberish, BigNumberish, AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'market', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'position', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  

  export interface IMorpho extends BaseContract {
    
    connect(runner?: ContractRunner | null): IMorpho;
    waitForDeployment(): Promise<this>;

    interface: IMorphoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    market: TypedContractMethod<
      [id: BytesLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {totalSupplyAssets: bigint, totalSupplyShares: bigint, totalBorrowAssets: bigint, totalBorrowShares: bigint, lastUpdate: bigint, fee: bigint }],
      'view'
    >
    

    
    position: TypedContractMethod<
      [id: BytesLike, user: AddressLike, ],
      [[bigint, bigint, bigint] & {supplyShares: bigint, borrowShares: bigint, collateral: bigint }],
      'view'
    >
    

    
    supply: TypedContractMethod<
      [marketParams: IMorpho.MarketParamsStruct, assets: BigNumberish, shares: BigNumberish, onBehalf: AddressLike, data: BytesLike, ],
      [[bigint, bigint] & {assetsSupplied: bigint, sharesSupplied: bigint }],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [marketParams: IMorpho.MarketParamsStruct, assets: BigNumberish, shares: BigNumberish, onBehalf: AddressLike, receiver: AddressLike, ],
      [[bigint, bigint] & {assetsWithdrawn: bigint, sharesWithdrawn: bigint }],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'market'): TypedContractMethod<
      [id: BytesLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {totalSupplyAssets: bigint, totalSupplyShares: bigint, totalBorrowAssets: bigint, totalBorrowShares: bigint, lastUpdate: bigint, fee: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'position'): TypedContractMethod<
      [id: BytesLike, user: AddressLike, ],
      [[bigint, bigint, bigint] & {supplyShares: bigint, borrowShares: bigint, collateral: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'supply'): TypedContractMethod<
      [marketParams: IMorpho.MarketParamsStruct, assets: BigNumberish, shares: BigNumberish, onBehalf: AddressLike, data: BytesLike, ],
      [[bigint, bigint] & {assetsSupplied: bigint, sharesSupplied: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [marketParams: IMorpho.MarketParamsStruct, assets: BigNumberish, shares: BigNumberish, onBehalf: AddressLike, receiver: AddressLike, ],
      [[bigint, bigint] & {assetsWithdrawn: bigint, sharesWithdrawn: bigint }],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }