/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { EpochMath, EpochMathInterface } from "../../libraries/EpochMath.js";

  const _abi = [
  {
    "inputs": [],
    "name": "MAX_PREMIUM_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_STRIKE_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MIN_STRIKE_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "STRIKE_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x604051600b810163000000c49182630000003e833981515f1a60730360275730905260738153f35b505050634e487b7160e01b5f525f60045260245ffdfe73000000000000000000000000000000000000000050600336116031575b5f5ffd5b506127116057565b506129046057565b5f3560e01c636fe1ca798113606057634c1620ae811460215763599faff403601d57612ee05b60805260206080f35b636fe1ca7a811460295763711b7a0c03601d576101f4605756fea26469706673582212200d16bff36f611e203c5a7c2b74c21ab69dce0cd5f620d0f47025628aff48070364736f6c637816736f6c783a302e312e383b736f6c633a302e382e33340047";

  
      type EpochMathConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: EpochMathConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class EpochMath__factory extends ContractFactory {
    
      constructor(...args: EpochMathConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<EpochMath & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): EpochMath__factory {
      return super.connect(runner) as EpochMath__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): EpochMathInterface {
      return new Interface(_abi) as EpochMathInterface;
    }
    
    override attach(address: string | Addressable): EpochMath {
      return super.attach(address) as EpochMath;
    }
  static connect(address: string, runner?: ContractRunner | null): EpochMath {
      return new Contract(address, _abi, runner) as unknown as EpochMath;
    }
  }

  
  