/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { EpochMath, EpochMathInterface } from "../../libraries/EpochMath.js";

  const _abi = [
  {
    "inputs": [],
    "name": "MAX_PREMIUM_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_STRIKE_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MIN_STRIKE_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "STRIKE_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234602057600e6024565b61026961002f82393081505061026990f35b602a565b60405190565b5f80fdfe60806040526004361015610013575b61022f565b61001d5f3561005c565b80634c1620ae14610057578063599faff4146100525780636fe1ca7a1461004d5763711b7a0c0361000e57610204565b6101a1565b61013e565b6100db565b60e01c90565b60405190565b5f80fd5b5f91031261007657565b610068565b90565b90565b90565b61009861009361009d9261007b565b610081565b61007e565b90565b6100ab612711610084565b90565b6100b66100a0565b90565b6100c29061007e565b9052565b91906100d9905f602085019401906100b9565b565b6100e636600461006c565b6101026100f16100ae565b6100f9610062565b918291826100c6565b0390f35b90565b61011d61011861012292610106565b610081565b61007e565b90565b610130612ee0610109565b90565b61013b610125565b90565b61014936600461006c565b610165610154610133565b61015c610062565b918291826100c6565b0390f35b90565b61018061017b61018592610169565b610081565b61007e565b90565b61019361290461016c565b90565b61019e610188565b90565b6101ac36600461006c565b6101c86101b7610196565b6101bf610062565b918291826100c6565b0390f35b90565b6101e36101de6101e8926101cc565b610081565b61007e565b90565b6101f66101f46101cf565b90565b6102016101eb565b90565b61020f36600461006c565b61022b61021a6101f9565b610222610062565b918291826100c6565b0390f35b5f80fdfea26469706673582212203d571be03813e95cb2102e77415ccfc11dba8464f87904aec4758fd554f174c664736f6c63430008220033";

  
      type EpochMathConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: EpochMathConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class EpochMath__factory extends ContractFactory {
    
      constructor(...args: EpochMathConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<EpochMath & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): EpochMath__factory {
      return super.connect(runner) as EpochMath__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): EpochMathInterface {
      return new Interface(_abi) as EpochMathInterface;
    }
    
    override attach(address: string | Addressable): EpochMath {
      return super.attach(address) as EpochMath;
    }
  static connect(address: string, runner?: ContractRunner | null): EpochMath {
      return new Contract(address, _abi, runner) as unknown as EpochMath;
    }
  }

  
  