/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { EpochMath, EpochMathInterface } from "../../libraries/EpochMath.js";

  const _abi = [
  {
    "inputs": [],
    "name": "MAX_PREMIUM_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_STRIKE_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MIN_STRIKE_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "STRIKE_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x61015061004d600b8282823980515f1a6073146041577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610610055575f3560e01c80634c1620ae14610059578063599faff4146100775780636fe1ca7a14610095578063711b7a0c146100b3575b5f5ffd5b6100616100d1565b60405161006e9190610101565b60405180910390f35b61007f6100d7565b60405161008c9190610101565b60405180910390f35b61009d6100dd565b6040516100aa9190610101565b60405180910390f35b6100bb6100e3565b6040516100c89190610101565b60405180910390f35b61271181565b612ee081565b61290481565b6101f481565b5f819050919050565b6100fb816100e9565b82525050565b5f6020820190506101145f8301846100f2565b9291505056fea2646970667358221220854e43913ac5c102ef54d55661cd2b7ed4ce1764a8eff55dd524cb61090372fd64736f6c63430008220033";

  
      type EpochMathConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: EpochMathConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class EpochMath__factory extends ContractFactory {
    
      constructor(...args: EpochMathConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<EpochMath & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): EpochMath__factory {
      return super.connect(runner) as EpochMath__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): EpochMathInterface {
      return new Interface(_abi) as EpochMathInterface;
    }
    
    override attach(address: string | Addressable): EpochMath {
      return super.attach(address) as EpochMath;
    }
  static connect(address: string, runner?: ContractRunner | null): EpochMath {
      return new Contract(address, _abi, runner) as unknown as EpochMath;
    }
  }

  
  