/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { Errors, ErrorsInterface } from "../../libraries/Errors.js";

  const _abi = [
  {
    "inputs": [],
    "name": "AlreadyAllocated",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AuctionNotClosed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "totalBps",
        "type": "uint256"
      }
    ],
    "name": "BadWeights",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "currentHigh",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "bid",
        "type": "uint256"
      }
    ],
    "name": "BidNotHigher",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "floor",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "bid",
        "type": "uint256"
      }
    ],
    "name": "BidTooLow",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EpochAlreadySettled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EpochLockedForWithdraw",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EpochNotLocked",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EpochNotOpen",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EpochNotSettleable",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FeeHookMisconfigured",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "currentBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "targetBps",
        "type": "uint256"
      }
    ],
    "name": "HysteresisLocked",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidConfig",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "decimals",
        "type": "uint8"
      }
    ],
    "name": "InvalidDecimals",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidDuration",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidStrike",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "dayOfWeek",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "hourUtc",
        "type": "uint256"
      }
    ],
    "name": "MarketClosed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoRedeemRequest",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotCurator",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotGuardian",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotKeeper",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotRouter",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotStrategy",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotVault",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NothingToWithdraw",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "price",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "prevPrice",
        "type": "uint256"
      }
    ],
    "name": "OracleDeviated",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OraclePaused",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "updatedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "deadline",
        "type": "uint256"
      }
    ],
    "name": "OracleStale",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OracleUnavailable",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RebalanceAwayFromTarget",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RedeemRequestPending",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "readyAt",
        "type": "uint256"
      }
    ],
    "name": "RequestTooFresh",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SequencerDown",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "capBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "requestedBps",
        "type": "uint256"
      }
    ],
    "name": "StrategyCapExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TransferFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Unauthorized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnknownStrategy",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "cap",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "requested",
        "type": "uint256"
      }
    ],
    "name": "VaultCapExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VaultPaused",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAmount",
    "type": "error"
  }
] as const;

  const _bytecode = "0x604051600b810163000000639182630000003e833981515f1a60730360275730905260738153f35b505050634e487b7160e01b5f525f60045260245ffdfe730000000000000000000000000000000000000000505f5ffdfea2646970667358221220493c362a60f96092c42b0d224990c7ecc5b08403d7988102e663124d0e97e95064736f6c637816736f6c783a302e312e383b736f6c633a302e382e33340047";

  
      type ErrorsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ErrorsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Errors__factory extends ContractFactory {
    
      constructor(...args: ErrorsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Errors & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Errors__factory {
      return super.connect(runner) as Errors__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ErrorsInterface {
      return new Interface(_abi) as ErrorsInterface;
    }
    
    override attach(address: string | Addressable): Errors {
      return super.attach(address) as Errors;
    }
  static connect(address: string, runner?: ContractRunner | null): Errors {
      return new Contract(address, _abi, runner) as unknown as Errors;
    }
  }

  
  