/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IEpochStrategy {
      
    export type EpochStruct = {id: BigNumberish, notional: BigNumberish, start: BigNumberish, auctionEnd: BigNumberish, expiry: BigNumberish, strike: BigNumberish, spot: BigNumberish, highBidder: AddressLike, highBid: BigNumberish, extensionCount: BigNumberish}

    export type EpochStructOutput = [id: bigint, notional: bigint, start: bigint, auctionEnd: bigint, expiry: bigint, strike: bigint, spot: bigint, highBidder: string, highBid: bigint, extensionCount: bigint] & {id: bigint, notional: bigint, start: bigint, auctionEnd: bigint, expiry: bigint, strike: bigint, spot: bigint, highBidder: string, highBid: bigint, extensionCount: bigint }
  
    }

  export interface IEpochStrategyInterface extends Interface {
    getFunction(nameOrSignature: "bid" | "closeAuction" | "currentEpoch" | "settleEpoch" | "startEpoch" | "state" | "vault"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionClosed" | "AuctionExtended" | "BidPlaced" | "EpochRolled" | "EpochSettled" | "EpochStarted"): EventFragment;

    encodeFunctionData(functionFragment: 'bid', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'closeAuction', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentEpoch', values?: undefined): string;
encodeFunctionData(functionFragment: 'settleEpoch', values?: undefined): string;
encodeFunctionData(functionFragment: 'startEpoch', values: [boolean]): string;
encodeFunctionData(functionFragment: 'state', values?: undefined): string;
encodeFunctionData(functionFragment: 'vault', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'bid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'state', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vault', data: BytesLike): Result;
  }

  
    export namespace AuctionClosedEvent {
      export type InputTuple = [epochId: BigNumberish, winner: AddressLike, premium: BigNumberish];
      export type OutputTuple = [epochId: bigint, winner: string, premium: bigint];
      export interface OutputObject {epochId: bigint, winner: string, premium: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionExtendedEvent {
      export type InputTuple = [epochId: BigNumberish, newEnd: BigNumberish];
      export type OutputTuple = [epochId: bigint, newEnd: bigint];
      export interface OutputObject {epochId: bigint, newEnd: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidPlacedEvent {
      export type InputTuple = [epochId: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [epochId: bigint, bidder: string, amount: bigint];
      export interface OutputObject {epochId: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochRolledEvent {
      export type InputTuple = [epochId: BigNumberish, notional: BigNumberish];
      export type OutputTuple = [epochId: bigint, notional: bigint];
      export interface OutputObject {epochId: bigint, notional: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochSettledEvent {
      export type InputTuple = [epochId: BigNumberish, spotAtExpiry: BigNumberish, payoff: BigNumberish, premium: BigNumberish, kept: BigNumberish];
      export type OutputTuple = [epochId: bigint, spotAtExpiry: bigint, payoff: bigint, premium: bigint, kept: bigint];
      export interface OutputObject {epochId: bigint, spotAtExpiry: bigint, payoff: bigint, premium: bigint, kept: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochStartedEvent {
      export type InputTuple = [epochId: BigNumberish, notional: BigNumberish, strike: BigNumberish, spot: BigNumberish, auctionEnd: BigNumberish];
      export type OutputTuple = [epochId: bigint, notional: bigint, strike: bigint, spot: bigint, auctionEnd: bigint];
      export interface OutputObject {epochId: bigint, notional: bigint, strike: bigint, spot: bigint, auctionEnd: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IEpochStrategy extends BaseContract {
    
    connect(runner?: ContractRunner | null): IEpochStrategy;
    waitForDeployment(): Promise<this>;

    interface: IEpochStrategyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bid: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    closeAuction: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    currentEpoch: TypedContractMethod<
      [],
      [IEpochStrategy.EpochStructOutput],
      'view'
    >
    

    
    settleEpoch: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    startEpoch: TypedContractMethod<
      [bypassMarketHours: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    state: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bid'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closeAuction'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'currentEpoch'): TypedContractMethod<
      [],
      [IEpochStrategy.EpochStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'settleEpoch'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startEpoch'): TypedContractMethod<
      [bypassMarketHours: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'state'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AuctionClosed'): TypedContractEvent<AuctionClosedEvent.InputTuple, AuctionClosedEvent.OutputTuple, AuctionClosedEvent.OutputObject>;
getEvent(key: 'AuctionExtended'): TypedContractEvent<AuctionExtendedEvent.InputTuple, AuctionExtendedEvent.OutputTuple, AuctionExtendedEvent.OutputObject>;
getEvent(key: 'BidPlaced'): TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
getEvent(key: 'EpochRolled'): TypedContractEvent<EpochRolledEvent.InputTuple, EpochRolledEvent.OutputTuple, EpochRolledEvent.OutputObject>;
getEvent(key: 'EpochSettled'): TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
getEvent(key: 'EpochStarted'): TypedContractEvent<EpochStartedEvent.InputTuple, EpochStartedEvent.OutputTuple, EpochStartedEvent.OutputObject>;

    filters: {
      
      'AuctionClosed(uint256,address,uint256)': TypedContractEvent<AuctionClosedEvent.InputTuple, AuctionClosedEvent.OutputTuple, AuctionClosedEvent.OutputObject>;
      AuctionClosed: TypedContractEvent<AuctionClosedEvent.InputTuple, AuctionClosedEvent.OutputTuple, AuctionClosedEvent.OutputObject>;
    

      'AuctionExtended(uint256,uint256)': TypedContractEvent<AuctionExtendedEvent.InputTuple, AuctionExtendedEvent.OutputTuple, AuctionExtendedEvent.OutputObject>;
      AuctionExtended: TypedContractEvent<AuctionExtendedEvent.InputTuple, AuctionExtendedEvent.OutputTuple, AuctionExtendedEvent.OutputObject>;
    

      'BidPlaced(uint256,address,uint256)': TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
      BidPlaced: TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
    

      'EpochRolled(uint256,uint256)': TypedContractEvent<EpochRolledEvent.InputTuple, EpochRolledEvent.OutputTuple, EpochRolledEvent.OutputObject>;
      EpochRolled: TypedContractEvent<EpochRolledEvent.InputTuple, EpochRolledEvent.OutputTuple, EpochRolledEvent.OutputObject>;
    

      'EpochSettled(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
      EpochSettled: TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
    

      'EpochStarted(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<EpochStartedEvent.InputTuple, EpochStartedEvent.OutputTuple, EpochStartedEvent.OutputObject>;
      EpochStarted: TypedContractEvent<EpochStartedEvent.InputTuple, EpochStartedEvent.OutputTuple, EpochStartedEvent.OutputObject>;
    
    };
  }