/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IEqueRouterInterface extends Interface {
    getFunction(nameOrSignature: "planAllocation" | "rebalance" | "registerStrategy" | "setToleranceBps" | "setWeights" | "strategyAssets" | "toleranceBps" | "weights"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Rebalanced" | "StrategyRegistered" | "WeightsSet"): EventFragment;

    encodeFunctionData(functionFragment: 'planAllocation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'rebalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerStrategy', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setToleranceBps', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setWeights', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'strategyAssets', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'toleranceBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'weights', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'planAllocation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rebalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setToleranceBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWeights', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'strategyAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'toleranceBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weights', data: BytesLike): Result;
  }

  
    export namespace RebalancedEvent {
      export type InputTuple = [vault: AddressLike, epochAssets: BigNumberish, lendingAssets: BigNumberish];
      export type OutputTuple = [vault: string, epochAssets: bigint, lendingAssets: bigint];
      export interface OutputObject {vault: string, epochAssets: bigint, lendingAssets: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyRegisteredEvent {
      export type InputTuple = [vault: AddressLike, strategy: AddressLike, capBps: BigNumberish];
      export type OutputTuple = [vault: string, strategy: string, capBps: bigint];
      export interface OutputObject {vault: string, strategy: string, capBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WeightsSetEvent {
      export type InputTuple = [vault: AddressLike, epochBps: BigNumberish, lendingBps: BigNumberish];
      export type OutputTuple = [vault: string, epochBps: bigint, lendingBps: bigint];
      export interface OutputObject {vault: string, epochBps: bigint, lendingBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IEqueRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): IEqueRouter;
    waitForDeployment(): Promise<this>;

    interface: IEqueRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    planAllocation: TypedContractMethod<
      [vault: AddressLike, ],
      [[string[], bigint[]] & {strategies: string[], amounts: bigint[] }],
      'view'
    >
    

    
    rebalance: TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registerStrategy: TypedContractMethod<
      [vault: AddressLike, strategy: AddressLike, capBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setToleranceBps: TypedContractMethod<
      [bps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setWeights: TypedContractMethod<
      [vault: AddressLike, epochBps: BigNumberish, lendingBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    strategyAssets: TypedContractMethod<
      [vault: AddressLike, strategy: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    toleranceBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    weights: TypedContractMethod<
      [vault: AddressLike, ],
      [[bigint, bigint] & {epochBps: bigint, lendingBps: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'planAllocation'): TypedContractMethod<
      [vault: AddressLike, ],
      [[string[], bigint[]] & {strategies: string[], amounts: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'rebalance'): TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerStrategy'): TypedContractMethod<
      [vault: AddressLike, strategy: AddressLike, capBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setToleranceBps'): TypedContractMethod<
      [bps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWeights'): TypedContractMethod<
      [vault: AddressLike, epochBps: BigNumberish, lendingBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'strategyAssets'): TypedContractMethod<
      [vault: AddressLike, strategy: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'toleranceBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'weights'): TypedContractMethod<
      [vault: AddressLike, ],
      [[bigint, bigint] & {epochBps: bigint, lendingBps: bigint }],
      'view'
    >;

    getEvent(key: 'Rebalanced'): TypedContractEvent<RebalancedEvent.InputTuple, RebalancedEvent.OutputTuple, RebalancedEvent.OutputObject>;
getEvent(key: 'StrategyRegistered'): TypedContractEvent<StrategyRegisteredEvent.InputTuple, StrategyRegisteredEvent.OutputTuple, StrategyRegisteredEvent.OutputObject>;
getEvent(key: 'WeightsSet'): TypedContractEvent<WeightsSetEvent.InputTuple, WeightsSetEvent.OutputTuple, WeightsSetEvent.OutputObject>;

    filters: {
      
      'Rebalanced(address,uint256,uint256)': TypedContractEvent<RebalancedEvent.InputTuple, RebalancedEvent.OutputTuple, RebalancedEvent.OutputObject>;
      Rebalanced: TypedContractEvent<RebalancedEvent.InputTuple, RebalancedEvent.OutputTuple, RebalancedEvent.OutputObject>;
    

      'StrategyRegistered(address,address,uint256)': TypedContractEvent<StrategyRegisteredEvent.InputTuple, StrategyRegisteredEvent.OutputTuple, StrategyRegisteredEvent.OutputObject>;
      StrategyRegistered: TypedContractEvent<StrategyRegisteredEvent.InputTuple, StrategyRegisteredEvent.OutputTuple, StrategyRegisteredEvent.OutputObject>;
    

      'WeightsSet(address,uint256,uint256)': TypedContractEvent<WeightsSetEvent.InputTuple, WeightsSetEvent.OutputTuple, WeightsSetEvent.OutputObject>;
      WeightsSet: TypedContractEvent<WeightsSetEvent.InputTuple, WeightsSetEvent.OutputTuple, WeightsSetEvent.OutputObject>;
    
    };
  }