/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface EpochMathInterface extends Interface {
    getFunction(nameOrSignature: "MAX_PREMIUM_BPS" | "MAX_STRIKE_BPS" | "MIN_STRIKE_BPS" | "STRIKE_BPS"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'MAX_PREMIUM_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_STRIKE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_STRIKE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'STRIKE_BPS', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_PREMIUM_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_STRIKE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_STRIKE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STRIKE_BPS', data: BytesLike): Result;
  }

  

  export interface EpochMath extends BaseContract {
    
    connect(runner?: ContractRunner | null): EpochMath;
    waitForDeployment(): Promise<this>;

    interface: EpochMathInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_PREMIUM_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_STRIKE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_STRIKE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    STRIKE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_PREMIUM_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_STRIKE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_STRIKE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'STRIKE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }