/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace OracleGuard {
      
    export type FeedStruct = {aggregator: AddressLike, sequencerFeed: AddressLike, heartbeat: BigNumberish, stalenessBuffer: BigNumberish, deviationBps: BigNumberish, checkMarketHours: boolean, checkPaused: boolean, checkSequencer: boolean}

    export type FeedStructOutput = [aggregator: string, sequencerFeed: string, heartbeat: bigint, stalenessBuffer: bigint, deviationBps: bigint, checkMarketHours: boolean, checkPaused: boolean, checkSequencer: boolean] & {aggregator: string, sequencerFeed: string, heartbeat: bigint, stalenessBuffer: bigint, deviationBps: bigint, checkMarketHours: boolean, checkPaused: boolean, checkSequencer: boolean }
  
    }

export declare namespace IEpochStrategy {
      
    export type EpochStruct = {id: BigNumberish, notional: BigNumberish, start: BigNumberish, auctionEnd: BigNumberish, expiry: BigNumberish, strike: BigNumberish, spot: BigNumberish, highBidder: AddressLike, highBid: BigNumberish, extensionCount: BigNumberish}

    export type EpochStructOutput = [id: bigint, notional: bigint, start: bigint, auctionEnd: bigint, expiry: bigint, strike: bigint, spot: bigint, highBidder: string, highBid: bigint, extensionCount: bigint] & {id: bigint, notional: bigint, start: bigint, auctionEnd: bigint, expiry: bigint, strike: bigint, spot: bigint, highBidder: string, highBid: bigint, extensionCount: bigint }
  
    }

  export interface EpochStrategyInterface extends Interface {
    getFunction(nameOrSignature: "CURATOR_ROLE" | "DEFAULT_ADMIN_ROLE" | "GUARDIAN_ROLE" | "KEEPER_ROLE" | "allocate" | "assetToken" | "auctionWindow" | "bid" | "claimablePremium" | "closeAuction" | "currentEpoch" | "currentEpochId" | "epoch" | "epochDuration" | "feed" | "floorBps" | "getRoleAdmin" | "grantRole" | "harvest" | "hasRole" | "liquidAssets" | "maxExtensions" | "nextEpochBoundaryView" | "renounceRole" | "revokeRole" | "setFloorBps" | "setVault" | "settleEpoch" | "startEpoch" | "state" | "supportsInterface" | "totalAssets" | "vault" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionClosed" | "AuctionExtended" | "BidPlaced" | "EpochRolled" | "EpochSettled" | "EpochStarted" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'CURATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'GUARDIAN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'KEEPER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'allocate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'assetToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctionWindow', values?: undefined): string;
encodeFunctionData(functionFragment: 'bid', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimablePremium', values?: undefined): string;
encodeFunctionData(functionFragment: 'closeAuction', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentEpoch', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentEpochId', values?: undefined): string;
encodeFunctionData(functionFragment: 'epoch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'epochDuration', values?: undefined): string;
encodeFunctionData(functionFragment: 'feed', values?: undefined): string;
encodeFunctionData(functionFragment: 'floorBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'harvest', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'liquidAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxExtensions', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextEpochBoundaryView', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setFloorBps', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'settleEpoch', values?: undefined): string;
encodeFunctionData(functionFragment: 'startEpoch', values: [boolean]): string;
encodeFunctionData(functionFragment: 'state', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'vault', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'CURATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GUARDIAN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'KEEPER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allocate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assetToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctionWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimablePremium', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentEpochId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochDuration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'floorBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'harvest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxExtensions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextEpochBoundaryView', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFloorBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'state', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace AuctionClosedEvent {
      export type InputTuple = [epochId: BigNumberish, winner: AddressLike, premium: BigNumberish];
      export type OutputTuple = [epochId: bigint, winner: string, premium: bigint];
      export interface OutputObject {epochId: bigint, winner: string, premium: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionExtendedEvent {
      export type InputTuple = [epochId: BigNumberish, newEnd: BigNumberish];
      export type OutputTuple = [epochId: bigint, newEnd: bigint];
      export interface OutputObject {epochId: bigint, newEnd: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidPlacedEvent {
      export type InputTuple = [epochId: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [epochId: bigint, bidder: string, amount: bigint];
      export interface OutputObject {epochId: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochRolledEvent {
      export type InputTuple = [epochId: BigNumberish, notional: BigNumberish];
      export type OutputTuple = [epochId: bigint, notional: bigint];
      export interface OutputObject {epochId: bigint, notional: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochSettledEvent {
      export type InputTuple = [epochId: BigNumberish, spotAtExpiry: BigNumberish, payoff: BigNumberish, premium: BigNumberish, kept: BigNumberish];
      export type OutputTuple = [epochId: bigint, spotAtExpiry: bigint, payoff: bigint, premium: bigint, kept: bigint];
      export interface OutputObject {epochId: bigint, spotAtExpiry: bigint, payoff: bigint, premium: bigint, kept: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochStartedEvent {
      export type InputTuple = [epochId: BigNumberish, notional: BigNumberish, strike: BigNumberish, spot: BigNumberish, auctionEnd: BigNumberish];
      export type OutputTuple = [epochId: bigint, notional: bigint, strike: bigint, spot: bigint, auctionEnd: bigint];
      export interface OutputObject {epochId: bigint, notional: bigint, strike: bigint, spot: bigint, auctionEnd: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EpochStrategy extends BaseContract {
    
    connect(runner?: ContractRunner | null): EpochStrategy;
    waitForDeployment(): Promise<this>;

    interface: EpochStrategyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CURATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    GUARDIAN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    KEEPER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allocate: TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'view'
    >
    

    
    assetToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    auctionWindow: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    bid: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimablePremium: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    closeAuction: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    currentEpoch: TypedContractMethod<
      [],
      [IEpochStrategy.EpochStructOutput],
      'view'
    >
    

    
    currentEpochId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    epoch: TypedContractMethod<
      [arg0: BigNumberish, ],
      [IEpochStrategy.EpochStructOutput],
      'view'
    >
    

    
    epochDuration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feed: TypedContractMethod<
      [],
      [[string, string, bigint, bigint, bigint, boolean, boolean, boolean] & {aggregator: string, sequencerFeed: string, heartbeat: bigint, stalenessBuffer: bigint, deviationBps: bigint, checkMarketHours: boolean, checkPaused: boolean, checkSequencer: boolean }],
      'view'
    >
    

    
    floorBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    harvest: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    liquidAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxExtensions: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextEpochBoundaryView: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFloorBps: TypedContractMethod<
      [bps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setVault: TypedContractMethod<
      [vault_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    settleEpoch: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    startEpoch: TypedContractMethod<
      [bypassMarketHours: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    state: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CURATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'GUARDIAN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'KEEPER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allocate'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'assetToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'auctionWindow'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bid'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimablePremium'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'closeAuction'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'currentEpoch'): TypedContractMethod<
      [],
      [IEpochStrategy.EpochStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'currentEpochId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'epoch'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [IEpochStrategy.EpochStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'epochDuration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feed'): TypedContractMethod<
      [],
      [[string, string, bigint, bigint, bigint, boolean, boolean, boolean] & {aggregator: string, sequencerFeed: string, heartbeat: bigint, stalenessBuffer: bigint, deviationBps: bigint, checkMarketHours: boolean, checkPaused: boolean, checkSequencer: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'floorBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'harvest'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'liquidAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxExtensions'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextEpochBoundaryView'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFloorBps'): TypedContractMethod<
      [bps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVault'): TypedContractMethod<
      [vault_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleEpoch'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startEpoch'): TypedContractMethod<
      [bypassMarketHours: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'state'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'AuctionClosed'): TypedContractEvent<AuctionClosedEvent.InputTuple, AuctionClosedEvent.OutputTuple, AuctionClosedEvent.OutputObject>;
getEvent(key: 'AuctionExtended'): TypedContractEvent<AuctionExtendedEvent.InputTuple, AuctionExtendedEvent.OutputTuple, AuctionExtendedEvent.OutputObject>;
getEvent(key: 'BidPlaced'): TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
getEvent(key: 'EpochRolled'): TypedContractEvent<EpochRolledEvent.InputTuple, EpochRolledEvent.OutputTuple, EpochRolledEvent.OutputObject>;
getEvent(key: 'EpochSettled'): TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
getEvent(key: 'EpochStarted'): TypedContractEvent<EpochStartedEvent.InputTuple, EpochStartedEvent.OutputTuple, EpochStartedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'AuctionClosed(uint256,address,uint256)': TypedContractEvent<AuctionClosedEvent.InputTuple, AuctionClosedEvent.OutputTuple, AuctionClosedEvent.OutputObject>;
      AuctionClosed: TypedContractEvent<AuctionClosedEvent.InputTuple, AuctionClosedEvent.OutputTuple, AuctionClosedEvent.OutputObject>;
    

      'AuctionExtended(uint256,uint256)': TypedContractEvent<AuctionExtendedEvent.InputTuple, AuctionExtendedEvent.OutputTuple, AuctionExtendedEvent.OutputObject>;
      AuctionExtended: TypedContractEvent<AuctionExtendedEvent.InputTuple, AuctionExtendedEvent.OutputTuple, AuctionExtendedEvent.OutputObject>;
    

      'BidPlaced(uint256,address,uint256)': TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
      BidPlaced: TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
    

      'EpochRolled(uint256,uint256)': TypedContractEvent<EpochRolledEvent.InputTuple, EpochRolledEvent.OutputTuple, EpochRolledEvent.OutputObject>;
      EpochRolled: TypedContractEvent<EpochRolledEvent.InputTuple, EpochRolledEvent.OutputTuple, EpochRolledEvent.OutputObject>;
    

      'EpochSettled(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
      EpochSettled: TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
    

      'EpochStarted(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<EpochStartedEvent.InputTuple, EpochStartedEvent.OutputTuple, EpochStartedEvent.OutputObject>;
      EpochStarted: TypedContractEvent<EpochStartedEvent.InputTuple, EpochStartedEvent.OutputTuple, EpochStartedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }